#! /bin/sh

sxhkd &

$HOME/.screenlayout/default.sh

pkill polybar

for disp in `bspc query -M --names`; do
    MONLST=""
    for num in `seq 9`; do
        MONLST="$MONLST $disp-$num"
    done
    bspc monitor -f $disp
    bspc monitor -d $MONLST
    polybar $disp &
done

feh Pictures/223A9918\ -\ Version\ 3.jpg --bg-fill

bspc rule -a hipchat4 desktop='DP-2-2-9'
bspc rule -a TeamViewer desktop='DP-2-2-9'

nm-applet &
blueman-applet &
hipchat4 &

#bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width            1
bspc config window_gap              4

bspc config top_padding             16

bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
